seed: 42
device: cuda:0
num_steps_per_env: 24
max_iterations: 4000
empirical_normalization: false
policy:
  class_name: VisionActorCritic
  init_noise_std: 1.0
  noise_std_type: scalar
  actor_hidden_dims:
  - 128
  - 128
  critic_hidden_dims:
  - 128
  - 128
  activation: lrelu
  img_res: !!python/tuple
  - 72
  - 96
  dim_hidden_input: 192
  use_auxiliary_loss: true
algorithm:
  class_name: PPOL2C2
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.0005
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  entropy_coef: 0.005
  desired_kl: 0.01
  max_grad_norm: 1.0
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  normalize_advantage_per_mini_batch: false
  symmetry_cfg: null
  rnd_cfg: null
clip_actions: null
save_interval: 500
experiment_name: racing_stage0
run_name: s1
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: true
load_run: 2025-12-15_17-07-17_s0
load_checkpoint: model_3999.pt
